import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatToolbarModule, 
         MatDialogModule, 
         MatButtonToggleModule, 
         MatBadgeModule, 
         MatFormFieldModule, 
         MatAutocompleteModule, 
         MatButtonModule, 
         MatProgressSpinnerModule, 
         MatSidenavModule, 
         MatIconModule, 
         MatListModule, 
         MatGridListModule, 
         MatInputModule, 
         MatSelectModule, 
         MatOptionModule,
         MatRadioModule, 
         MatCheckboxModule, 
         MatDatepickerModule, 
         MatNativeDateModule, 
         MatCardModule, 
         MatMenuModule, 
         MatTableModule, 
         MatPaginatorModule, 
         MatSortModule } from '@angular/material';


@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatToolbarModule, 
    MatDialogModule, 
    MatButtonToggleModule, 
    MatBadgeModule, 
    MatFormFieldModule, 
    MatAutocompleteModule, 
    MatButtonModule, 
    MatProgressSpinnerModule, 
    MatSidenavModule, 
    MatIconModule, 
    MatListModule, 
    MatGridListModule, 
    MatInputModule, 
    MatSelectModule, 
    MatOptionModule, 
    MatRadioModule, 
    MatCheckboxModule, 
    MatDatepickerModule, 
    MatNativeDateModule, 
    MatCardModule, 
    MatMenuModule, 
    MatTableModule, 
    MatPaginatorModule, 
    MatSortModule
  ],
  exports: [
    
    MatToolbarModule, 
    MatDialogModule, 
    MatButtonToggleModule, 
    MatBadgeModule, 
    MatFormFieldModule, 
    MatAutocompleteModule, 
    MatButtonModule, 
    MatProgressSpinnerModule, 
    MatSidenavModule, 
    MatIconModule, 
    MatListModule, 
    MatGridListModule, 
    MatInputModule, 
    MatSelectModule, 
    MatOptionModule, 
    MatRadioModule, 
    MatCheckboxModule, 
    MatDatepickerModule, 
    MatNativeDateModule, 
    MatCardModule, 
    MatMenuModule, 
    MatTableModule, 
    MatPaginatorModule, 
    MatSortModule
  ]
})
export class MaterialModule { }
